# Generated by Django 3.1.7 on 2021-03-18 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210317_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ManyToManyField(blank=True, related_name='issue_type', to='tracker.Issue_type', validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='tracker.status', validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Заголовок'),
        ),
    ]
