# Generated by Django 3.1.7 on 2021-04-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_project_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('project_user_add', 'Можно добавлять пользователя в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
